[simplematrixbotlib.config]
timeout = 65536
join_on_invite = true
encryption_enabled = true
emoji_verify = true
ignore_unverified_devices = false
store_path = "./crypto_store/"
allowlist = []
blocklist = []
first_sync_full = false
